title: "질문"
body:
  - type: markdown
    attributes:
      value: |
        ### 📝 토론 참여자 목록
        ```
        @kgy1008
        @5win 
        @kargowild 
        @nak-honest
        @ParkChaerin129
        ```
        ---

  - type: input
    id: participants
    attributes:
      label: 😀 참여자
      description: 위 목록에서 토론에 참여할 분들을 복사하여 태그해주세요
      placeholder: "@username1 @username2"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### 🚀 결론 작성
